name: start-server
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - "*"

jobs:
    test:
        runs_on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 18.14.0
            - name: Install dependencies
              run: npm i
            - name: Run tests
              run: npm test
